Django/website_w_auth_images/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/5/
    path('<int:pk>/', views.QuestionDetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # ex: /polls/login or /polls/logout
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
]

Django/website_w_auth_images/website/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
urlpatterns = [
    path('polls/', include("polls.urls")),
    path('admin/', admin.site.urls),

]

Django/website_w_auth_images/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class User(models.Model):
    username = models.CharField(max_length=200, unique=True)
    password = models.TextField()
    email = models.EmailField(max_length=200, unique=True)

Django/website_w_auth_images/polls/views.py
from django.contrib.auth.hashers import check_password, make_password
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView
from .models import Question, Choice, User


def index(request):
    context = {
        "course": "CSE-30332",
        "semester": "Spring 2024",
    }
    return render(request, "polls/index.html", context)


class IndexView(ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]

class QuestionDetailView(DetailView):
    model = Question
    template_name = "polls/detail.html"

class ResultsView(DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, question_id):
    # make sure it is authenticated, if not authenticated, send to log-in page
    if request.session.get("user", None) is None:
        return HttpResponseRedirect(reverse("polls:login"))
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

## ADDED FOR BLOG APP: LOGIN / LOGOUT
# https://stackoverflow.com/a/43793754
def login(request):
    errors = None
    if request.POST:
        # Create a model instance and populate it with data from the request
        uname = request.POST["username"]
        pwd = request.POST["password"]
        user = User.objects.filter(username=uname)

        if len(user) > 0 and check_password(pwd, user[0].password):
            # create a new session
            request.session["user"] = uname
            return HttpResponseRedirect(reverse('polls:index'))
        else:
            errors = [('authentication', "Login error")]

    return render(request, 'polls/login.html', {'errors': errors})

def logout(request):
    # remove the logged-in user information
    del request.session["user"]
    return HttpResponseRedirect(reverse("polls:login"))

Django/website_w_auth_images/polls/templates/polls/base.html
<!DOCTYPE html>
<html>
<head>


    <title>{% block title %}Poll app{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
        html, body {
            height: 100%;
            align-items: center;
            padding: 40px;
            background-color: #f5f5f5;
            text-align: center;
        }

        input {
            margin: 10px 0px;
        }
    </style>
    {% block css_header %}{% endblock %}
</head>
<body>
    {% if request.session.user %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light text-center">
        <span class="title"><b>Current Logged In User:</b>
            {{ request.session.user }}
        </span>
        (<a class="" href="{% url 'polls:logout' %}">
            Logout
        </a>)
    </nav>
    {% endif %}
    <div id="content">
        {% block content %}{% endblock %}
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
</body>
</html>

Django/website_w_auth_images/polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% block title %}Vote for {{ question.question_text }}{% endblock %}
{% block content %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
            {% if error_message %}.
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
{% endblock %}

Django/website_w_auth_images/polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% block title %}Last published questions{% endblock %}
{% block content %}
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li>
                <a href="{% url 'polls:detail' question.id %}">
                    {{ question.question_text }}
                </a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

Django/website_w_auth_images/polls/templates/polls/login.html
{% extends "polls/base.html" %}
{% block content %}
<h1>User login</h1>
{% if errors %}
<div class="alert alert-danger d-flex align-items-center" role="alert">
    <ul>
        {% for error in errors %}
        <li> {{ error.0 }}: {{error.1}}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}
<form class="m-auto col-md-3" method="POST">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
    <div class="form-floating">
        <input type="text" class="form-control" id="username" name="username" placeholder="username">
        <label for="username">Username</label>
    </div>
    <div class="form-floating">
        <input type="password" class="form-control" id="password" name="password"  placeholder="Password">
        <label for="password">Password</label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
</form>

{% endblock %}

Django/website_w_auth_images/polls/templates/polls/results.html
{% extends "polls/base.html" %}
{% block title %}View results for {{ question.question_text }}{% endblock %}
{% block content %}
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>
                {{ choice.choice_text }} --
                {{ choice.votes }}
                vote{{ choice.votes|pluralize }}
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">
        Vote again?
    </a>
{% endblock %}